// web-vben/apps/web-ele/src/views/agentmesh/profile/index.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';

import MetricCard from '#/components/agentmesh/MetricCard.vue';
import PageHeader from '#/components/agentmesh/PageHeader.vue';
import { useAgentMeshAuthStore } from '#/store/agentmesh-auth';
import { useAgentMeshResourcesStore } from '#/store/agentmesh-resources';

const router = useRouter();
const auth = useAgentMeshAuthStore();
const resources = useAgentMeshResourcesStore();
const initials = computed(() =>
  (auth.user?.displayName || auth.user?.email || 'AM')
    .slice(0, 2)
    .toUpperCase(),
);
const completed = computed(
  () =>
    resources.tasks.filter(
      (item) => String(item.status).toUpperCase() === 'COMPLETED',
    ).length,
);
onMounted(() => resources.refreshAll());
</script>

<template>
  <div class="am-page profile-page">
    <PageHeader
      eyebrow="PROFILE"
      title="个人主页"
      description="查看账户信息、工作概况，并快速进入常用设置。"
    />
    <section class="profile-hero am-card">
      <div class="profile-avatar">{{ initials }}</div>
      <div>
        <h2>{{ auth.user?.displayName || 'AgentMesh 用户' }}</h2>
        <p>{{ auth.user?.email }}</p>
        <el-tag type="success" round>
          {{ auth.user?.status || 'ACTIVE' }}
        </el-tag>
      </div>
      <div class="hero-actions">
        <el-button @click="router.push('/agentmesh/model-settings')">
          模型设置
</el-button><el-button type="primary" @click="router.push('/agentmesh/workspace')">
          返回工作台
        </el-button>
      </div>
    </section>
    <div class="am-metrics" style="margin-top: 16px">
      <MetricCard label="项目" :value="resources.projects.length" /><MetricCard
        label="会话"
        :value="resources.conversations.length"
      /><MetricCard
        label="智能体"
        :value="resources.agents.length"
      /><MetricCard label="已完成任务" :value="completed" tone="success" />
    </div>
    <div class="profile-grid">
      <section class="am-card quick-card">
        <h3>常用入口</h3>
        <button @click="router.push('/agentmesh/workspace')">
          <span>⌂</span>
          <div><b>工作台</b><small>继续最近会话或新建任务</small></div>
          <em>→</em>
</button><button @click="router.push('/agentmesh/model-settings')">
          <span>▤</span>
          <div><b>模型设置</b><small>管理个人 BYOK 模型服务</small></div>
          <em>→</em>
</button><button @click="router.push('/agentmesh/governance')">
          <span>⬡</span>
          <div><b>治理与安全</b><small>项目权限、成本和审计</small></div>
          <em>→</em>
        </button>
      </section>
      <section class="am-card quick-card">
        <h3>最近会话</h3>
        <button
          v-for="conversation in resources.conversations.slice(0, 5)"
          :key="conversation.id"
          @click="router.push('/agentmesh/workspace')"
        >
          <span>◌</span>
          <div>
            <b>{{ conversation.title }}</b><small>{{
              conversation.lastMessageAt
                ? new Date(conversation.lastMessageAt).toLocaleString()
                : '暂无消息'
            }}</small>
          </div>
          <em>→</em>
        </button>
        <div v-if="resources.conversations.length === 0" class="mini-empty">
          还没有会话
        </div>
      </section>
    </div>
  </div>
</template>

<style scoped>
.profile-hero {
  display: flex;
  gap: 16px;
  align-items: center;
  padding: 22px;
}

.profile-avatar {
  display: grid;
  place-items: center;
  width: 72px;
  height: 72px;
  font-size: 22px;
  font-weight: 850;
  color: var(--am-primary);
  background: linear-gradient(135deg, #dcd4ff, #f5f1ff);
  border-radius: 22px;
}

.profile-hero h2 {
  margin: 0 0 4px;
}

.profile-hero p {
  margin: 0 0 7px;
  font-size: 11px;
  color: var(--am-muted);
}

.hero-actions {
  display: flex;
  gap: 8px;
  margin-left: auto;
}

.profile-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
  margin-top: 16px;
}

.quick-card {
  padding: 16px;
}

.quick-card h3 {
  margin: 0 0 10px;
}

.quick-card button {
  display: grid;
  grid-template-columns: 34px minmax(0, 1fr) auto;
  gap: 8px;
  align-items: center;
  width: 100%;
  padding: 10px 0;
  text-align: left;
  cursor: pointer;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--am-border);
}

.quick-card button > span {
  display: grid;
  place-items: center;
  width: 34px;
  height: 34px;
  color: var(--am-primary);
  background: var(--am-primary-soft);
  border-radius: 9px;
}

.quick-card b,
.quick-card small {
  display: block;
}

.quick-card b {
  font-size: 10px;
}

.quick-card small {
  margin-top: 2px;
  font-size: 8px;
  color: var(--am-muted);
}

.quick-card em {
  font-style: normal;
  color: var(--am-muted);
}

.mini-empty {
  padding: 20px;
  font-size: 10px;
  color: var(--am-muted);
  text-align: center;
}

@media (max-width: 800px) {
  .profile-grid {
    grid-template-columns: 1fr;
  }

  .profile-hero {
    flex-wrap: wrap;
    align-items: flex-start;
  }

  .hero-actions {
    width: 100%;
    margin-left: 0;
  }
}
</style>

// web-react/src/features/profile/Profile.tsx
import type {
  Agent,
  Conversation,
  Project,
  Task,
  User,
} from "../../types";
import { Icon } from "../../components/common/Icon";

export function Profile({
  user,
  projects,
  conversations,
  agents,
  tasks,
  onNavigate,
}: {
  user: User;
  projects: Project[];
  conversations: Conversation[];
  agents: Agent[];
  tasks: Task[];
  onNavigate: (page: "workspace" | "model-settings" | "governance") => void;
}) {
  const initials = user.displayName.slice(0, 2).toUpperCase();
  const metrics = [
    { label: "项目", value: projects.length },
    { label: "会话", value: conversations.length },
    { label: "智能体", value: agents.length },
    { label: "任务记录", value: tasks.length },
  ];

  return (
    <div className="page calm-page profile-page">
      <header className="calm-page-head profile-page-head">
        <div className="calm-page-copy">
          <span className="calm-kicker">个人主页</span>
          <h1>你的 AgentMesh 工作概览</h1>
          <p>查看账户信息与个人工作概况，并快速进入常用设置。</p>
        </div>
      </header>

      <section className="profile-identity-card">
        <span className="profile-avatar-large">{initials}</span>
        <div className="profile-identity-copy">
          <h2>{user.displayName}</h2>
          <p>{user.email}</p>
          <span className={`profile-account-state ${user.status === "active" ? "ok" : "idle"}`}>
            <i />
            账户状态：{user.status === "active" ? "正常" : user.status || "未知"}
          </span>
        </div>
      </section>

      <section className="profile-section">
        <div className="profile-section-head">
          <div>
            <span className="calm-kicker">工作概览</span>
            <h2>当前个人空间</h2>
          </div>
        </div>
        <div className="profile-metric-grid">
          {metrics.map((metric) => (
            <article className="profile-metric-card" key={metric.label}>
              <strong>{metric.value}</strong>
              <span>{metric.label}</span>
            </article>
          ))}
        </div>
      </section>

      <section className="profile-section">
        <div className="profile-section-head">
          <div>
            <span className="calm-kicker">常用入口</span>
            <h2>继续你的工作</h2>
          </div>
        </div>
        <div className="profile-shortcut-grid">
          <button type="button" onClick={() => onNavigate("workspace")}>
            <span><Icon name="workspace" size={17} /></span>
            <div>
              <strong>工作台</strong>
              <small>继续最近的会话、项目和任务。</small>
            </div>
          </button>
          <button type="button" onClick={() => onNavigate("model-settings")}>
            <span><Icon name="server" size={17} /></span>
            <div>
              <strong>模型设置</strong>
              <small>管理你的个人模型服务和自动路由。</small>
            </div>
          </button>
          <button type="button" onClick={() => onNavigate("governance")}>
            <span><Icon name="shield" size={17} /></span>
            <div>
              <strong>治理与安全</strong>
              <small>查看组织、权限、配额与安全边界。</small>
            </div>
          </button>
        </div>
      </section>
    </div>
  );
}
