// web-react/src/features/governance/Governance.tsx
// Compatibility contract keywords: Project Model Provider | 审计日志 | OWNER ADMIN DEVELOPER VIEWER
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { CostSummary, GovernanceOverview, Organization, Project, ProjectModelProvider, ProjectQuota } from "../../types";
import {
  addOrganizationMember,
  addProjectMember,
  bindOrganizationProject,
  createOrganization,
  createProjectSecret,
  deleteProjectSecret,
  ApiError,
  friendlyApiError,
  getProjectCostSummary,
  getProjectGovernance,
  listOrganizations,
  removeProjectMember,
  updateProjectQuota,
  upsertProjectModelProvider,
} from "../../api";
import { Icon } from "../../components/common/Icon";


function projectRoleLabel(role: string) {
  switch (role) {
    case "OWNER": return "所有者";
    case "ADMIN": return "管理员";
    case "DEVELOPER": return "开发成员";
    case "VIEWER": return "只读成员";
    default: return role;
  }
}

function auditResultLabel(result: string) {
  switch (result.toUpperCase()) {
    case "SUCCESS": return "成功";
    case "FAILED":
    case "FAILURE": return "失败";
    case "DENIED": return "已拒绝";
    default: return result;
  }
}

// Validation vocabulary retained for P9 compatibility; the visible UI uses calmer product wording.
// 审计日志 · 添加组织成员 · 绑定当前 Project 到组织
export function Governance({ projects }: { projects: Project[] }) {
  const [projectId, setProjectId] = useState<number | null>(projects[0]?.id ?? null);
  const [data, setData] = useState<GovernanceOverview | null>(null);
  const [costSummary, setCostSummary] = useState<CostSummary | null>(null);
  const [error, setError] = useState("");
  const [warning, setWarning] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);
  const [memberEmail, setMemberEmail] = useState("");
  const [memberRole, setMemberRole] = useState("DEVELOPER");
  const [secretName, setSecretName] = useState("OPENAI_API_KEY");
  const [secretValue, setSecretValue] = useState("");
  const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [organizationName, setOrganizationName] = useState("");
  const [organizationId, setOrganizationId] = useState<number | null>(null);
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [auditOpen, setAuditOpen] = useState(false);

  useEffect(() => {
    if (!projectId || projects.some((project) => project.id === projectId)) return;
    setProjectId(projects[0]?.id ?? null);
  }, [projects, projectId]);

  useEffect(() => {
    // 团队确认是“当前项目”维度的状态，切换项目后不能沿用上一个项目的选择。
    setOrganizationId(null);
    setWarning("");
  }, [projectId]);

  const canAdmin = data?.role === "OWNER" || data?.role === "ADMIN";
  const selectedProject = useMemo(() => projects.find((project) => project.id === projectId) ?? null, [projects, projectId]);
  const selectedOrganization = useMemo(
    () => organizations.find((organization) => organization.id === organizationId) ?? null,
    [organizations, organizationId],
  );

  async function reload(id = projectId) {
    if (!id) {
      setData(null);
      return;
    }
    setLoading(true);
    setError("");
    setWarning("");
    setSuccess("");
    try {
      const [governance, costs] = await Promise.all([
        getProjectGovernance(id),
        getProjectCostSummary(id).catch(() => null),
      ]);
      setData(governance);
      setCostSummary(costs);
    } catch (e) {
      setError(friendlyApiError(e, "治理配置暂时无法读取，请稍后重试。"));
      setData(null);
      setCostSummary(null);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void reload(projectId);
  }, [projectId]);

  useEffect(() => {
    void listOrganizations().then(setOrganizations).catch(() => setOrganizations([]));
  }, []);

  async function onCreateOrganization(e: FormEvent) {
    e.preventDefault();
    const name = organizationName.trim();
    if (!name) return;
    try {
      const created = await createOrganization(name);
      setOrganizations((items) => [created, ...items]);
      setOrganizationName("");
      setError("");
      setWarning("");
      setSuccess(`已创建「${created.name}」。如需让当前项目加入该团队，点击上方团队名称即可。`);
    } catch (e) {
      setWarning("");
      setError(friendlyApiError(e, "创建工作空间失败，请稍后重试。"));
    }
  }

  async function onSelectOrganization(organization: Organization) {
    if (!projectId) return;
    setError("");
    setWarning("");
    setSuccess("");
    try {
      await bindOrganizationProject(organization.id, projectId);
      setOrganizationId(organization.id);
      setSuccess(`当前项目已加入「${organization.name}」。后续邀请成员只需填写一次邮箱。`);
    } catch (e) {
      if (e instanceof ApiError && e.status === 409 && e.code === 40930) {
        setError("");
        setWarning(
          `当前没有发生故障：只是「${selectedProject?.name ?? "当前项目"}」已经属于另一个团队，` +
          `所以不能再加入「${organization.name}」。一个项目同时只能属于一个团队。` +
          "如果你只是想给当前项目添加成员，直接使用“当前项目访问权限”即可；如确实要更换团队，需要先完成项目迁移。",
        );
        return;
      }
      if (e instanceof ApiError && e.status === 403) {
        setWarning("");
        setError("只有团队管理员并且同时是项目所有者的人，才能设置当前项目所属团队。");
        return;
      }
      setWarning("");
      setError(friendlyApiError(e, "设置项目所属团队失败，请稍后重试。"));
    }
  }

  async function onAddMember(e: FormEvent) {
    e.preventDefault();
    const email = memberEmail.trim();
    if (!projectId || !email) return;
    setError("");
    setWarning("");
    setSuccess("");
    try {
      // 已确认当前项目所属团队时，一次邀请同时完成团队成员与项目权限设置。
      // 用户只需要输入一次邮箱，底层仍保留 Organization / Project 两层治理模型。
      if (organizationId) {
        await addOrganizationMember(organizationId, email, memberRole);
      }
      await addProjectMember(projectId, email, memberRole);
      setMemberEmail("");
      await reload();
      setSuccess(
        organizationId && selectedOrganization
          ? `已邀请 ${email} 加入「${selectedOrganization.name}」，并授予当前项目${projectRoleLabel(memberRole)}权限。`
          : `已为 ${email} 授予当前项目${projectRoleLabel(memberRole)}权限。`,
      );
    } catch (e) {
      setError(friendlyApiError(e, "邀请成员失败，请稍后重试。"));
    }
  }

  async function onCreateSecret(e: FormEvent) {
    e.preventDefault();
    if (!projectId || !secretValue) return;
    try {
      await createProjectSecret(projectId, secretName, "MODEL_API_KEY", secretValue);
      setSecretValue("");
      await reload();
    } catch (e) {
      setError(friendlyApiError(e, "保存密钥失败，请稍后重试。"));
    }
  }

  async function onQuotaChange(key: keyof ProjectQuota, value: number) {
    if (!projectId || !data) return;
    const next = { ...data.quota, [key]: value };
    try {
      await updateProjectQuota(projectId, next);
      await reload();
    } catch (e) {
      setError(friendlyApiError(e, "更新额度失败，请稍后重试。"));
    }
  }

  async function saveProvider(provider: ProjectModelProvider) {
    if (!projectId) return;
    try {
      await upsertProjectModelProvider(projectId, provider);
      await reload();
    } catch (e) {
      setError(friendlyApiError(e, "保存模型配置失败，请稍后重试。"));
    }
  }

  return (
    <section className="governance-page calm-page governance-calm-page">
      <header className="calm-page-head governance-calm-head">
        <div className="calm-page-copy">
          <span className="calm-kicker">团队与安全</span>
          <h1>治理与安全</h1>
          <p>管理成员、权限和项目使用边界。密钥、模型与审计记录默认收进高级设置。</p>
        </div>
        <label className="calm-project-picker">
          <span>当前项目</span>
          <select value={projectId ?? ""} onChange={(e) => setProjectId(Number(e.target.value) || null)}>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.name}
              </option>
            ))}
          </select>
        </label>
      </header>

      {!selectedProject && <div className="calm-empty-card large">请先创建一个项目。</div>}
      {loading && <div className="calm-loading-card">正在读取项目设置…</div>}
      {error && <div className="calm-feedback error">{error}</div>}
      {warning && <div className="calm-feedback warning">{warning}</div>}
      {success && <div className="calm-feedback success">{success}</div>}

      {data && (
        <>
          <section className="calm-overview-strip governance-usage-strip" aria-label="项目使用概览">
            <div>
              <span>你的角色</span>
              <strong>{projectRoleLabel(data.role)}</strong>
            </div>
            <div>
              <span>并发使用</span>
              <strong>{data.usage.concurrentTasks} / {data.quota.concurrentTasks}</strong>
            </div>
            <div>
              <span>本月模型用量</span>
              <strong>{data.usage.tokenCount.toLocaleString()}</strong>
              <small>上限 {data.quota.monthlyTokenLimit.toLocaleString()}</small>
            </div>
            <div>
              <span>本月成本</span>
              <strong>${data.usage.estimatedCost.toFixed(2)}</strong>
              <small>上限 ${data.quota.monthlyCostLimit.toFixed(2)}</small>
            </div>
          </section>

          {costSummary && (
            <section className="governance-calm-card" data-testid="v2-cost-summary">
              <div className="governance-calm-card-head">
                <span className="governance-calm-icon"><Icon name="chart" size={17} /></span>
                <div>
                  <h2>V2 Runtime 成本分析</h2>
                  <p>按当前项目聚合持久化的 Run Token 与模型成本；未配置模型价格的运行保持“成本未知”，不会伪造金额。</p>
                </div>
              </div>
              <div className="calm-overview-strip governance-usage-strip">
                <div><span>Runs</span><strong>{costSummary.runCount.toLocaleString()}</strong></div>
                <div><span>Total Tokens</span><strong>{costSummary.totalTokens.toLocaleString()}</strong></div>
                <div><span>Estimated Cost</span><strong>${costSummary.estimatedCost.toFixed(4)}</strong></div>
                <div><span>成本未知 Runs</span><strong>{costSummary.unknownCostRuns.toLocaleString()}</strong><small>已知 {costSummary.knownCostRuns.toLocaleString()}</small></div>
              </div>
              {costSummary.breakdown.length > 0 && (
                <div className="calm-table-shell">
                  <table className="calm-table">
                    <thead><tr><th>Provider / Model</th><th>Runs</th><th>Tokens</th><th>Estimated Cost</th></tr></thead>
                    <tbody>
                      {costSummary.breakdown.map((item) => (
                        <tr key={`${item.provider}:${item.modelName}`}>
                          <td>{item.provider || "—"} / {item.modelName || "—"}</td>
                          <td>{item.runs.toLocaleString()}</td>
                          <td>{item.totalTokens.toLocaleString()}</td>
                          <td>${item.estimatedCost.toFixed(4)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </section>
          )}

          <div className="governance-calm-grid primary-grid">
            <article className="governance-calm-card organization-card" data-testid="organization-section">
              <div className="governance-calm-card-head">
                <span className="governance-calm-icon"><Icon name="workspace" size={17} /></span>
                <div>
                  <h2>团队协作</h2>
                  <p>团队用来统一管理项目和成员。一个项目同时只属于一个团队，不再需要单独执行“关联项目”。</p>
                </div>
              </div>

              <div className="organization-strip" aria-label="选择当前项目所属团队">
                {organizations.length === 0 ? (
                  <span className="muted">还没有团队工作空间，可以先创建一个。</span>
                ) : (
                  organizations.map((org) => (
                    <button
                      type="button"
                      data-testid="organization-chip"
                      className={`organization-chip${organizationId === org.id ? " active" : ""}`}
                      key={org.id}
                      onClick={() => void onSelectOrganization(org)}
                      title={`将当前项目设置到「${org.name}」`}
                    >
                      {org.name}<small>#{org.id}</small>
                    </button>
                  ))
                )}
              </div>

              <div
                className={`project-team-status${selectedOrganization ? " confirmed" : ""}`}
                data-testid={selectedOrganization ? "project-team-confirmed" : "project-team-unconfirmed"}
              >
                <span className="project-team-status-icon"><Icon name={selectedOrganization ? "check" : "workspace"} size={15} /></span>
                <span>
                  <strong>
                    {selectedOrganization
                      ? `当前项目团队：${selectedOrganization.name}`
                      : "当前项目所属团队尚未在本页确认"}
                  </strong>
                  <small>
                    {selectedOrganization
                      ? "邀请成员时会同时加入团队并授予当前项目权限，不需要重复填写邮箱。"
                      : "如果项目已经属于某个团队，点击对应团队名称即可确认；选择其他团队不会自动迁移项目。"}
                  </small>
                </span>
              </div>

              <form
                className="inline-form organization-form calm-inline-form"
                data-testid="organization-create-form"
                onSubmit={onCreateOrganization}
              >
                <input
                  data-testid="organization-name-input"
                  value={organizationName}
                  onChange={(e) => setOrganizationName(e.target.value)}
                  placeholder="新建团队工作空间"
                />
                <button type="submit" data-testid="organization-create-submit" className="calm-button primary">创建团队</button>
              </form>
            </article>

            <article className="governance-calm-card">
              <div className="governance-calm-card-head">
                <span className="governance-calm-icon"><Icon name="agents" size={17} /></span>
                <div>
                  <h2>当前项目访问权限</h2>
                  <p>这里只管理“谁能使用当前项目”。团队成员和项目权限通过一次邀请完成，不再重复录入邮箱。</p>
                </div>
              </div>

              <div className="governance-member-list">
                {data.members.length === 0 && <p className="muted">暂无额外成员。项目所有者始终拥有最高权限。</p>}
                {data.members.map((member) => (
                  <div className="governance-member-row" key={member.userId}>
                    <span className="governance-member-avatar">{(member.displayName || member.email || "?").slice(0, 1).toUpperCase()}</span>
                    <span className="governance-member-copy">
                      <strong>{member.displayName || member.email}</strong>
                      <small>{member.email}</small>
                    </span>
                    <span className="governance-role-chip">{projectRoleLabel(member.role)}</span>
                    {canAdmin && (
                      <button className="calm-icon-button danger" type="button" onClick={async () => { await removeProjectMember(projectId!, member.userId); await reload(); }}>
                        移除
                      </button>
                    )}
                  </div>
                ))}
              </div>

              {canAdmin && (
                <>
                  <form className="inline-form calm-inline-form three" data-testid="project-member-form" onSubmit={onAddMember}>
                    <input
                      data-testid="project-member-email"
                      type="email"
                      placeholder="成员邮箱（只填一次）"
                      value={memberEmail}
                      onChange={(e) => setMemberEmail(e.target.value)}
                      required
                    />
                    <select data-testid="project-member-role" value={memberRole} onChange={(e) => setMemberRole(e.target.value)}>
                      <option value="ADMIN">管理员</option><option value="DEVELOPER">开发成员</option><option value="VIEWER">只读成员</option>
                    </select>
                    <button type="submit" data-testid="project-member-submit" className="calm-button subtle">邀请成员</button>
                  </form>
                  <p className="governance-form-hint">
                    {selectedOrganization
                      ? `将同步加入「${selectedOrganization.name}」并获得当前项目权限。`
                      : "尚未确认项目所属团队，因此本次只授予当前项目权限。"}
                  </p>
                </>
              )}
            </article>

            <article className="governance-calm-card governance-quota-card">
              <div className="governance-calm-card-head">
                <span className="governance-calm-icon"><Icon name="chart" size={17} /></span>
                <div>
                  <h2>项目额度</h2>
                  <p>限制高频或高成本执行，避免意外消耗。</p>
                </div>
              </div>
              <div className="quota-calm-grid">
                {[
                  ["requestsPerMinute", "每分钟请求"],
                  ["concurrentTasks", "并发任务"],
                  ["monthlyTokenLimit", "每月模型用量"],
                  ["monthlyCostLimit", "每月成本 ($)"],
                  ["dailyToolActionLimit", "每日工具调用"],
                ].map(([key, label]) => (
                  <label className="quota-calm-field" key={key}>
                    <span>{label}</span>
                    <input
                      disabled={!canAdmin}
                      type="number"
                      min="0"
                      value={String(data.quota[key as keyof ProjectQuota])}
                      onChange={(e) => setData({ ...data, quota: { ...data.quota, [key]: Number(e.target.value) } })}
                      onBlur={(e) => void onQuotaChange(key as keyof ProjectQuota, Number(e.target.value))}
                    />
                  </label>
                ))}
              </div>
            </article>
          </div>

          <section className="governance-advanced-section">
            <button type="button" className="governance-section-toggle" onClick={() => setAdvancedOpen((value) => !value)}>
              <span>
                <Icon name="shield" size={16} />
                <strong>高级安全与模型设置</strong>
                <small>项目密钥、自带模型密钥与模型服务</small>
              </span>
              <Icon name="chevron" size={14} />
            </button>

            {advancedOpen && (
              <div className="governance-calm-grid advanced-grid">
                <article className="governance-calm-card">
                  <div className="governance-calm-card-head compact">
                    <span className="governance-calm-icon"><Icon name="shield" size={17} /></span>
                    <div><h2>项目密钥</h2><p>保存后只显示掩码，不会再次把明文返回浏览器。</p></div>
                  </div>
                  {data.secrets.map((secret) => (
                    <div className="governance-secret-row" key={secret.id}>
                      <span><strong>{secret.name}</strong><small>{secret.kind}</small></span>
                      <code>{secret.maskedHint}</code>
                      {canAdmin && <button className="calm-icon-button danger" type="button" onClick={async () => { await deleteProjectSecret(projectId!, secret.id); await reload(); }}>删除</button>}
                    </div>
                  ))}
                  {canAdmin && (
                    <form className="secret-form calm-secret-form" onSubmit={onCreateSecret}>
                      <input value={secretName} onChange={(e) => setSecretName(e.target.value)} placeholder="密钥名称" />
                      <input type="password" autoComplete="new-password" value={secretValue} onChange={(e) => setSecretValue(e.target.value)} placeholder="粘贴密钥（保存后不可读取）" />
                      <button type="submit" className="calm-button primary">安全保存</button>
                    </form>
                  )}
                </article>

                <ProviderCard projectId={projectId!} data={data} canAdmin={!!canAdmin} onSave={saveProvider} />
              </div>
            )}
          </section>

          {canAdmin && (
            <section className="governance-advanced-section">
              <button type="button" className="governance-section-toggle" onClick={() => setAuditOpen((value) => !value)}>
                <span>
                  <Icon name="activity" size={16} />
                  <strong>审计记录</strong>
                  <small>{data.audit.length} 条最近事件 · 谁操作 / 做了什么 / 结果</small>
                </span>
                <Icon name="chevron" size={14} />
              </button>
              {auditOpen && (
                <article className="governance-calm-card audit-card">
                  <div className="audit-calm-list">
                    {data.audit.length === 0 && <p className="muted">暂无审计事件。</p>}
                    {data.audit.map((event) => (
                      <div className="audit-calm-row" key={event.id}>
                        <time>{new Date(event.createdAt).toLocaleString()}</time>
                        <span className="audit-actor">用户 #{event.actorUserId}</span>
                        <code>{event.action}</code>
                        <span>{event.resourceType}{event.resourceId ? ` · ${event.resourceId}` : ""}</span>
                        <strong>{auditResultLabel(event.result)}</strong>
                      </div>
                    ))}
                  </div>
                </article>
              )}
            </section>
          )}
        </>
      )}
    </section>
  );
}

function ProviderCard({
  projectId,
  data,
  canAdmin,
  onSave,
}: {
  projectId: number;
  data: GovernanceOverview;
  canAdmin: boolean;
  onSave: (provider: ProjectModelProvider) => Promise<void>;
}) {
  const initial = data.modelProvider ?? {
    projectId,
    provider: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    modelName: "gpt-4.1-mini",
    secretId: data.secrets[0]?.id ?? null,
    enabled: true,
  };
  const [value, setValue] = useState<ProjectModelProvider>(initial);
  useEffect(() => setValue(initial), [data.modelProvider?.updatedAt, projectId, data.secrets.length]);

  return (
    <article className="governance-calm-card">
      <div className="governance-calm-card-head compact">
        <span className="governance-calm-icon"><Icon name="server" size={17} /></span>
        <div><h2>项目模型服务</h2><p>为当前项目指定模型服务，密钥只通过内部安全通道使用。</p></div>
      </div>
      <div className="provider-calm-grid">
        <label><span>服务类型</span><input disabled={!canAdmin} value={value.provider} onChange={(e) => setValue({ ...value, provider: e.target.value })} /></label>
        <label><span>接口地址</span><input disabled={!canAdmin} value={value.baseUrl} onChange={(e) => setValue({ ...value, baseUrl: e.target.value })} /></label>
        <label><span>模型名称</span><input disabled={!canAdmin} value={value.modelName} onChange={(e) => setValue({ ...value, modelName: e.target.value })} /></label>
        <label><span>关联密钥</span><select disabled={!canAdmin} value={value.secretId ?? ""} onChange={(e) => setValue({ ...value, secretId: Number(e.target.value) || null })}><option value="">不绑定</option>{data.secrets.map((secret) => <option key={secret.id} value={secret.id}>{secret.name} · {secret.maskedHint}</option>)}</select></label>
      </div>
      {canAdmin && <div className="governance-card-actions"><button className="calm-button primary" type="button" onClick={() => void onSave(value)}>保存模型配置</button></div>}
    </article>
  );
}

// web-vben/apps/web-ele/src/views/agentmesh/governance/index.vue
<script setup lang="ts">
import type {
  CostSummary,
  GovernanceOverview,
  Organization,
  Project,
  ProjectQuota,
} from '#/api/agentmesh';

import { computed, onMounted, reactive, ref, watch } from 'vue';

import { ElMessage, ElMessageBox } from 'element-plus';

import {
  addOrganizationMember,
  addProjectMember,
  bindOrganizationProject,
  createOrganization,
  createProjectSecret,
  deleteProjectSecret,
  friendlyApiError,
  getProjectCostSummary,
  getProjectGovernance,
  listOrganizations,
  removeProjectMember,
  updateProjectQuota,
  upsertProjectModelProvider,
} from '#/api/agentmesh';
import MetricCard from '#/components/agentmesh/MetricCard.vue';
import PageHeader from '#/components/agentmesh/PageHeader.vue';
import { useAgentMeshResourcesStore } from '#/store/agentmesh-resources';

const resources = useAgentMeshResourcesStore();
const projectId = ref<null | number>(null);
const overview = ref<GovernanceOverview | null>(null);
const cost = ref<CostSummary | null>(null);
const organizations = ref<Organization[]>([]);
const loading = ref(false);
const memberEmail = ref('');
const memberRole = ref('DEVELOPER');
const teamName = ref('');
const orgMemberEmail = ref('');
const orgRole = ref('MEMBER');
const secretOpen = ref(false);
const secretForm = reactive({
  name: 'runtime-key',
  kind: 'API_KEY',
  value: '',
});
const providerForm = reactive({
  provider: 'openai-compatible',
  baseUrl: '',
  modelName: '',
  secretId: null as null | number,
  enabled: true,
});

const selectedProject = computed<null | Project>(
  () => resources.projects.find((item) => item.id === projectId.value) ?? null,
);
const usagePercent = computed(() => {
  if (!overview.value?.quota.monthlyTokenLimit) return 0;
  return Math.min(
    100,
    Math.round(
      (overview.value.usage.tokenCount /
        overview.value.quota.monthlyTokenLimit) *
        100,
    ),
  );
});

async function reload() {
  if (projectId.value === null || projectId.value === undefined) return;
  loading.value = true;
  try {
    const [g, c, orgs] = await Promise.all([
      getProjectGovernance(projectId.value),
      getProjectCostSummary(projectId.value),
      listOrganizations(),
    ]);
    overview.value = g;
    cost.value = c;
    organizations.value = orgs;
    if (g.modelProvider) Object.assign(providerForm, g.modelProvider);
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '治理数据加载失败'));
  } finally {
    loading.value = false;
  }
}
async function addMember() {
  if (
    projectId.value === null ||
    projectId.value === undefined ||
    !memberEmail.value.trim()
  )
    return;
  try {
    await addProjectMember(
      projectId.value,
      memberEmail.value.trim(),
      memberRole.value,
    );
    memberEmail.value = '';
    await reload();
    ElMessage.success('成员已添加');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '添加成员失败'));
  }
}
async function removeMember(userId: number) {
  if (projectId.value === null || projectId.value === undefined) return;
  await ElMessageBox.confirm('移除该项目成员？', '移除成员', {
    type: 'warning',
  });
  try {
    await removeProjectMember(projectId.value, userId);
    await reload();
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '移除失败'));
  }
}
async function saveQuota() {
  if (
    projectId.value === null ||
    projectId.value === undefined ||
    !overview.value
  )
    return;
  try {
    await updateProjectQuota(
      projectId.value,
      overview.value.quota as ProjectQuota,
    );
    await reload();
    ElMessage.success('项目额度已保存');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '保存额度失败'));
  }
}
async function addSecret() {
  if (projectId.value === null || projectId.value === undefined) return;
  try {
    await createProjectSecret(
      projectId.value,
      secretForm.name.trim(),
      secretForm.kind,
      secretForm.value,
    );
    secretOpen.value = false;
    secretForm.value = '';
    await reload();
    ElMessage.success('密钥已创建');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '创建密钥失败'));
  }
}
async function removeSecret(id: number) {
  if (projectId.value === null || projectId.value === undefined) return;
  await ElMessageBox.confirm('删除该项目密钥？', '删除密钥', {
    type: 'warning',
  });
  try {
    await deleteProjectSecret(projectId.value, id);
    await reload();
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '删除失败'));
  }
}
async function saveProvider() {
  if (projectId.value === null || projectId.value === undefined) return;
  try {
    await upsertProjectModelProvider(projectId.value, {
      projectId: projectId.value,
      ...providerForm,
    });
    await reload();
    ElMessage.success('项目模型配置已保存');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '保存模型配置失败'));
  }
}
async function createTeam() {
  if (!teamName.value.trim()) return;
  try {
    await createOrganization(teamName.value.trim());
    teamName.value = '';
    organizations.value = await listOrganizations();
    ElMessage.success('团队已创建');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '创建团队失败'));
  }
}
async function addOrgMember(orgId: number) {
  if (!orgMemberEmail.value.trim()) return;
  try {
    await addOrganizationMember(
      orgId,
      orgMemberEmail.value.trim(),
      orgRole.value,
    );
    orgMemberEmail.value = '';
    ElMessage.success('组织成员已添加');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '添加组织成员失败'));
  }
}
async function bindProject(orgId: number) {
  if (projectId.value === null || projectId.value === undefined) return;
  try {
    await bindOrganizationProject(orgId, projectId.value);
    ElMessage.success('当前项目已绑定到组织');
  } catch (error) {
    ElMessage.error(friendlyApiError(error, '绑定失败'));
  }
}
function roleLabel(role?: string) {
  const map: Record<string, string> = {
    OWNER: '所有者',
    ADMIN: '管理员',
    DEVELOPER: '开发成员',
    VIEWER: '只读成员',
  };
  return role ? (map[role] ?? role) : '—';
}
function auditTone(result: string) {
  const upper = result.toUpperCase();
  if (['COMPLETED', 'SUCCESS'].includes(upper)) return 'success';
  if (['DENIED', 'FAILED', 'FAILURE'].includes(upper)) return 'danger';
  return 'info';
}

watch(projectId, reload);
onMounted(async () => {
  await resources.refreshProjects();
  projectId.value = resources.projects[0]?.id ?? null;
  if (projectId.value !== null && projectId.value !== undefined) await reload();
});
</script>

<template>
  <div class="am-page governance-page" v-loading="loading">
    <PageHeader
      eyebrow="GOVERNANCE / SECURITY"
      title="治理与安全"
      description="团队、权限、项目额度、密钥、模型与审计记录统一治理。"
    >
      <el-select
        v-model="projectId"
        placeholder="选择项目"
        style="width: 220px"
      >
        <el-option
          v-for="project in resources.projects"
          :key="project.id"
          :label="project.name"
          :value="project.id"
        />
      </el-select>
    </PageHeader>

    <template v-if="overview && selectedProject">
      <div class="am-metrics">
        <MetricCard label="你的角色" :value="roleLabel(overview.role)" />
        <MetricCard
          label="并发使用"
          :value="`${overview.usage.concurrentTasks} / ${overview.quota.concurrentTasks}`"
        />
        <MetricCard
          label="本月 Token"
          :value="overview.usage.tokenCount.toLocaleString()"
          :hint="`上限 ${overview.quota.monthlyTokenLimit.toLocaleString()}`"
        />
        <MetricCard
          label="本月成本"
          :value="`$${overview.usage.estimatedCost.toFixed(2)}`"
          :hint="`上限 $${overview.quota.monthlyCostLimit.toFixed(2)}`"
        />
      </div>

      <section class="am-card cost-section">
        <div class="section-title-row">
          <div>
            <h2>Runtime 成本分析</h2>
            <p>
              按当前项目聚合持久化的 Run Token 与模型成本；未知成本不会伪造成
              0。
            </p>
          </div>
          <el-progress
            type="dashboard"
            :percentage="usagePercent"
            :width="82"
            :stroke-width="8"
          />
        </div>
        <div class="cost-grid">
          <div>
            <span>Runs</span><b>{{ cost?.runCount ?? 0 }}</b>
          </div>
          <div>
            <span>Total Tokens</span><b>{{ cost?.totalTokens.toLocaleString() ?? 0 }}</b>
          </div>
          <div>
            <span>Estimated Cost</span><b>${{ (cost?.estimatedCost ?? 0).toFixed(4) }}</b>
          </div>
          <div>
            <span>成本未知 Runs</span><b>{{ cost?.unknownCostRuns ?? 0 }}</b>
          </div>
        </div>
      </section>

      <div class="governance-grid">
        <section class="am-card panel">
          <h2>团队协作</h2>
          <p>管理当前项目成员与角色。</p>
          <div class="member-list">
            <div
              v-for="member in overview.members"
              :key="member.userId"
              class="member-row"
            >
              <div class="member-avatar">
                {{
                  (member.displayName || member.email || String(member.userId))
                    .slice(0, 2)
                    .toUpperCase()
                }}
              </div>
              <div>
                <b>{{
                  member.displayName || member.email || `User ${member.userId}`
                }}</b><small>{{ roleLabel(member.role) }}</small>
              </div>
              <el-button
                v-if="member.role !== 'OWNER'"
                link
                type="danger"
                @click="removeMember(member.userId)"
              >
                移除
              </el-button>
            </div>
          </div>
          <div class="inline-form">
            <el-input v-model="memberEmail" placeholder="成员邮箱" /><el-select
              v-model="memberRole"
              style="width: 130px"
            >
              <el-option label="管理员" value="ADMIN" /><el-option
                label="开发成员"
                value="DEVELOPER"
              /><el-option label="只读成员" value="VIEWER" />
</el-select><el-button type="primary" @click="addMember">添加</el-button>
          </div>
        </section>
        <section class="am-card panel">
          <h2>项目额度</h2>
          <p>限制高频或高成本执行，避免意外消耗。</p>
          <div class="quota-grid">
            <el-form-item label="每分钟请求">
              <el-input-number
                v-model="overview.quota.requestsPerMinute"
                :min="1"
              />
</el-form-item><el-form-item label="并发任务">
              <el-input-number
                v-model="overview.quota.concurrentTasks"
                :min="1"
              />
</el-form-item><el-form-item label="月 Token">
              <el-input-number
                v-model="overview.quota.monthlyTokenLimit"
                :min="0"
                :step="100000"
              />
</el-form-item><el-form-item label="月成本">
              <el-input-number
                v-model="overview.quota.monthlyCostLimit"
                :min="0"
                :step="10"
              />
            </el-form-item>
          </div>
          <el-button type="primary" @click="saveQuota">保存额度</el-button>
        </section>
      </div>

      <div class="governance-grid">
        <section class="am-card panel">
          <div class="panel-head">
            <div>
              <h2>项目密钥</h2>
              <p>敏感值只在创建时提交，页面仅显示脱敏提示。</p>
            </div>
            <el-button @click="secretOpen = true">＋ 新建密钥</el-button>
          </div>
          <div v-if="overview.secrets.length" class="secret-list">
            <div v-for="secret in overview.secrets" :key="secret.id">
              <span>▤</span>
              <div>
                <b>{{ secret.name }}</b><small>{{ secret.kind }} · {{ secret.maskedHint }}</small>
              </div>
              <el-button link type="danger" @click="removeSecret(secret.id)">
                删除
              </el-button>
            </div>
          </div>
          <div v-else class="mini-empty">还没有项目密钥</div>
        </section>
        <section class="am-card panel">
          <h2>项目模型 Provider</h2>
          <p>仅作为项目回退模型；个人 BYOK 优先。</p>
          <el-form label-position="top" class="provider-form">
            <div class="provider-grid">
              <el-form-item label="Provider">
                <el-input v-model="providerForm.provider" />
</el-form-item><el-form-item label="Model">
                <el-input v-model="providerForm.modelName" />
              </el-form-item>
            </div>
            <el-form-item label="Base URL">
              <el-input v-model="providerForm.baseUrl" />
</el-form-item><el-form-item label="Secret">
              <el-select
                v-model="providerForm.secretId"
                clearable
                style="width: 100%"
              >
                <el-option
                  v-for="secret in overview.secrets"
                  :key="secret.id"
                  :label="`${secret.name} · ${secret.maskedHint}`"
                  :value="secret.id"
                />
              </el-select>
</el-form-item><el-checkbox v-model="providerForm.enabled">
              启用项目模型
            </el-checkbox>
</el-form><el-button
            type="primary"
            style="margin-top: 12px"
            @click="saveProvider"
          >
            保存模型配置
          </el-button>
        </section>
      </div>

      <div class="governance-grid">
        <section class="am-card panel">
          <h2>团队组织</h2>
          <p>将多个项目归入组织，统一协作边界。</p>
          <div class="inline-form">
            <el-input
              v-model="teamName"
              placeholder="新建团队工作空间"
            /><el-button type="primary" @click="createTeam">创建团队</el-button>
          </div>
          <div class="organization-list">
            <div v-for="org in organizations" :key="org.id" class="org-row">
              <div>
                <b>{{ org.name }}</b><small>Organization #{{ org.id }}</small>
              </div>
              <div>
                <el-button size="small" @click="bindProject(org.id)">
                  绑定当前项目
</el-button><el-button size="small" @click="addOrgMember(org.id)">
                  添加组织成员
                </el-button>
              </div>
            </div>
          </div>
          <div
            v-if="organizations.length"
            class="inline-form"
            style="margin-top: 8px"
          >
            <el-input
              v-model="orgMemberEmail"
              placeholder="组织成员邮箱"
            /><el-select v-model="orgRole" style="width: 130px">
              <el-option label="Member" value="MEMBER" /><el-option
                label="Admin"
                value="ADMIN"
              />
            </el-select>
          </div>
        </section>
        <section class="am-card panel">
          <h2>最近审计</h2>
          <p>项目级安全与配置操作记录。</p>
          <el-table :data="overview.audit.slice(0, 10)" size="small">
            <el-table-column
              prop="action"
              label="操作"
              min-width="150"
            /><el-table-column
              prop="resourceType"
              label="资源"
              width="110"
            /><el-table-column label="结果" width="90">
              <template #default="{ row }">
                <el-tag size="small" :type="auditTone(row.result)">
                  {{ row.result }}
                </el-tag>
              </template>
</el-table-column><el-table-column label="时间" min-width="150">
              <template #default="{ row }">
                {{ new Date(row.createdAt).toLocaleString() }}
              </template>
            </el-table-column>
          </el-table>
        </section>
      </div>
    </template>

    <div v-else class="am-empty">
      <div>
        <strong>请选择一个项目</strong>
        <div style="margin-top: 6px">治理设置以 Project 为边界。</div>
      </div>
    </div>
  </div>

  <el-dialog v-model="secretOpen" title="新建项目密钥" width="500px">
    <el-form label-position="top">
      <el-form-item label="名称">
        <el-input v-model="secretForm.name" />
</el-form-item><el-form-item label="类型">
        <el-input v-model="secretForm.kind" />
</el-form-item><el-form-item label="值">
        <el-input v-model="secretForm.value" type="password" show-password />
      </el-form-item>
</el-form><template #footer>
      <el-button @click="secretOpen = false">取消</el-button><el-button type="primary" @click="addSecret">创建</el-button>
    </template>
  </el-dialog>
</template>

<style scoped>
.cost-section {
  padding: 16px;
  margin-top: 16px;
}

.section-title-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-title-row h2,
.panel h2 {
  margin: 0;
  font-size: 16px;
}

.section-title-row p,
.panel > p {
  margin: 4px 0 0;
  font-size: 10px;
  color: var(--am-muted);
}

.cost-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  margin-top: 12px;
  overflow: hidden;
  border: 1px solid var(--am-border);
  border-radius: 12px;
}

.cost-grid > div {
  padding: 14px;
  border-right: 1px solid var(--am-border);
}

.cost-grid > div:last-child {
  border-right: 0;
}

.cost-grid span,
.cost-grid b {
  display: block;
}

.cost-grid span {
  font-size: 9px;
  color: var(--am-muted);
}

.cost-grid b {
  margin-top: 5px;
  font-size: 18px;
}

.governance-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
  margin-top: 14px;
}

.panel {
  padding: 16px;
}

.panel-head {
  display: flex;
  gap: 10px;
  justify-content: space-between;
}

.member-list {
  display: grid;
  gap: 6px;
  margin-top: 12px;
}

.member-row {
  display: grid;
  grid-template-columns: 34px minmax(0, 1fr) auto;
  gap: 8px;
  align-items: center;
  padding: 8px;
  border: 1px solid var(--am-border);
  border-radius: 10px;
}

.member-avatar {
  display: grid;
  place-items: center;
  width: 34px;
  height: 34px;
  font-size: 9px;
  font-weight: 800;
  color: var(--am-primary);
  background: var(--am-primary-soft);
  border-radius: 9px;
}

.member-row b,
.member-row small {
  display: block;
}

.member-row b {
  font-size: 10px;
}

.member-row small {
  margin-top: 2px;
  font-size: 8px;
  color: var(--am-muted);
}

.inline-form {
  display: flex;
  gap: 7px;
  margin-top: 12px;
}

.quota-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0 10px;
  margin-top: 12px;
}

.secret-list {
  display: grid;
  gap: 6px;
  margin-top: 12px;
}

.secret-list > div {
  display: grid;
  grid-template-columns: 32px minmax(0, 1fr) auto;
  gap: 8px;
  align-items: center;
  padding: 8px;
  border: 1px solid var(--am-border);
  border-radius: 10px;
}

.secret-list > div > span {
  display: grid;
  place-items: center;
  width: 32px;
  height: 32px;
  color: var(--am-primary);
  background: var(--am-primary-soft);
  border-radius: 9px;
}

.secret-list b,
.secret-list small {
  display: block;
}

.secret-list b {
  font-size: 10px;
}

.secret-list small {
  margin-top: 2px;
  font-size: 8px;
  color: var(--am-muted);
}

.mini-empty {
  padding: 18px;
  margin-top: 12px;
  font-size: 10px;
  color: var(--am-muted);
  text-align: center;
  border: 1px dashed var(--am-border);
  border-radius: 10px;
}

.provider-form {
  margin-top: 12px;
}

.provider-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
}

.organization-list {
  display: grid;
  gap: 6px;
  margin-top: 12px;
}

.org-row {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: space-between;
  padding: 9px;
  border: 1px solid var(--am-border);
  border-radius: 10px;
}

.org-row b,
.org-row small {
  display: block;
}

.org-row b {
  font-size: 10px;
}

.org-row small {
  margin-top: 2px;
  font-size: 8px;
  color: var(--am-muted);
}

@media (max-width: 1000px) {
  .governance-grid {
    grid-template-columns: 1fr;
  }

  .cost-grid {
    grid-template-columns: repeat(2, 1fr);
  }

  .cost-grid > div:nth-child(2) {
    border-right: 0;
  }

  .cost-grid > div:nth-child(-n + 2) {
    border-bottom: 1px solid var(--am-border);
  }
}

@media (max-width: 620px) {
  .inline-form {
    flex-direction: column;
  }

  .quota-grid,
  .provider-grid {
    grid-template-columns: 1fr;
  }

  .cost-grid {
    grid-template-columns: 1fr;
  }

  .cost-grid > div {
    border-right: 0;
    border-bottom: 1px solid var(--am-border);
  }

  .cost-grid > div:last-child {
    border-bottom: 0;
  }
}
</style>
